"""
HTML template for timeline visualization.

Generates a self-contained HTML file with embedded CSS and JavaScript.
"""

from __future__ import annotations

from timetracer.timeline.generator import TimelineData


def render_timeline_html(data: TimelineData) -> str:
    """
    Render timeline data as a standalone HTML file.

    Args:
        data: Timeline data to visualize.

    Returns:
        Complete HTML string.
    """
    _events_to_json(data)

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Timetracer Timeline - {data.title}</title>
    <style>
{_get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Timetracer Timeline</h1>
            <div class="request-info">
                <span class="method {data.method.lower()}">{data.method}</span>
                <span class="path">{data.path}</span>
                <span class="status status-{_status_class(data.response_status)}">{data.response_status}</span>
            </div>
            <div class="meta">
                <span>Duration: <strong>{data.total_duration_ms:.1f}ms</strong></span>
                <span>Events: <strong>{data.event_count}</strong></span>
                <span>Recorded: {data.recorded_at}</span>
            </div>
        </header>

        <div class="timeline-container">
            <div class="timeline-header">
                <span>0ms</span>
                <span>{data.total_duration_ms / 2:.0f}ms</span>
                <span>{data.total_duration_ms:.0f}ms</span>
            </div>
            <div class="timeline" id="timeline">
                <!-- Main request bar -->
                <div class="timeline-row main-request">
                    <div class="label">Request</div>
                    <div class="bar-container">
                        <div class="bar status-{_status_class(data.response_status)}"
                             style="left: 0%; width: 100%;"
                             title="Total: {data.total_duration_ms:.1f}ms">
                        </div>
                    </div>
                </div>

                <!-- Dependency events -->
                {_render_events(data)}
            </div>
        </div>

        <div class="events-list">
            <h2>Events Detail</h2>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Type</th>
                        <th>URL/Label</th>
                        <th>Start</th>
                        <th>Duration</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {_render_events_table(data)}
                </tbody>
            </table>
        </div>

        <footer>
            <p>Generated by <strong>Timetracer</strong> v1.3.0</p>
        </footer>
    </div>

    <script>
{_get_js()}
    </script>
</body>
</html>'''


def _status_class(status: int) -> str:
    """Get CSS class for status code."""
    if status < 300:
        return "success"
    elif status < 400:
        return "redirect"
    elif status < 500:
        return "client-error"
    else:
        return "server-error"


def _events_to_json(data: TimelineData) -> str:
    """Convert events to JSON for JavaScript."""
    import json
    return json.dumps(data.to_dict()["events"])


def _render_events(data: TimelineData) -> str:
    """Render timeline event bars."""
    if not data.events or data.total_duration_ms == 0:
        return ""

    lines = []
    for event in data.events:
        left_pct = (event.start_ms / data.total_duration_ms) * 100
        width_pct = (event.duration_ms / data.total_duration_ms) * 100
        width_pct = max(width_pct, 0.5)  # Minimum visible width

        status_class = _status_class(event.status) if event.status else "unknown"
        error_class = "error" if event.is_error else ""

        # Shorten label
        label = event.label
        if len(label) > 40:
            label = label[:37] + "..."

        lines.append(f'''
                <div class="timeline-row">
                    <div class="label" title="{event.label}">#{event.id} {event.event_type}</div>
                    <div class="bar-container">
                        <div class="bar {status_class} {error_class}"
                             style="left: {left_pct:.1f}%; width: {width_pct:.1f}%;"
                             title="{event.label}&#10;Start: {event.start_ms:.1f}ms&#10;Duration: {event.duration_ms:.1f}ms&#10;Status: {event.status}">
                        </div>
                    </div>
                </div>''')

    return "\n".join(lines)


def _render_events_table(data: TimelineData) -> str:
    """Render events table rows."""
    if not data.events:
        return '<tr><td colspan="6">No events</td></tr>'

    lines = []
    for event in data.events:
        status_class = _status_class(event.status) if event.status else "unknown"
        error_indicator = "[ERR]" if event.is_error else ""

        url_display = event.url or event.label
        if len(url_display) > 60:
            url_display = url_display[:57] + "..."

        lines.append(f'''
                    <tr class="{status_class}">
                        <td>{event.id}</td>
                        <td>{event.event_type}</td>
                        <td title="{event.url}">{url_display}</td>
                        <td>{event.start_ms:.1f}ms</td>
                        <td>{event.duration_ms:.1f}ms</td>
                        <td><span class="status status-{status_class}">{event.status}</span> {error_indicator}</td>
                    </tr>''')

    return "\n".join(lines)


def _get_css() -> str:
    """Get embedded CSS styles."""
    return '''
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #eee;
            min-height: 100vh;
            padding: 2rem;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        header {
            margin-bottom: 2rem;
        }

        h1 {
            font-size: 1.8rem;
            margin-bottom: 1rem;
            color: #fff;
        }

        h2 {
            font-size: 1.3rem;
            margin: 2rem 0 1rem;
            color: #fff;
        }

        .request-info {
            display: flex;
            align-items: center;
            gap: 1rem;
            margin-bottom: 0.5rem;
        }

        .method {
            padding: 0.3rem 0.8rem;
            border-radius: 4px;
            font-weight: bold;
            font-size: 0.9rem;
        }

        .method.get { background: #22c55e; color: #000; }
        .method.post { background: #3b82f6; color: #fff; }
        .method.put { background: #f59e0b; color: #000; }
        .method.delete { background: #ef4444; color: #fff; }
        .method.patch { background: #a855f7; color: #fff; }

        .path {
            font-family: monospace;
            font-size: 1.1rem;
        }

        .status {
            padding: 0.2rem 0.6rem;
            border-radius: 4px;
            font-weight: bold;
            font-size: 0.85rem;
        }

        .status-success { background: #22c55e; color: #000; }
        .status-redirect { background: #f59e0b; color: #000; }
        .status-client-error { background: #ef4444; color: #fff; }
        .status-server-error { background: #dc2626; color: #fff; }
        .status-unknown { background: #6b7280; color: #fff; }

        .meta {
            display: flex;
            gap: 2rem;
            color: #94a3b8;
            font-size: 0.9rem;
        }

        .timeline-container {
            background: rgba(255,255,255,0.05);
            border-radius: 8px;
            padding: 1.5rem;
            margin: 1rem 0;
        }

        .timeline-header {
            display: flex;
            justify-content: space-between;
            color: #64748b;
            font-size: 0.8rem;
            margin-bottom: 0.5rem;
            padding-left: 120px;
        }

        .timeline-row {
            display: flex;
            align-items: center;
            margin: 0.4rem 0;
        }

        .timeline-row .label {
            width: 120px;
            font-size: 0.8rem;
            color: #94a3b8;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        .bar-container {
            flex: 1;
            height: 24px;
            background: rgba(255,255,255,0.1);
            border-radius: 4px;
            position: relative;
        }

        .bar {
            position: absolute;
            height: 100%;
            border-radius: 4px;
            cursor: pointer;
            transition: opacity 0.2s;
        }

        .bar:hover {
            opacity: 0.8;
        }

        .bar.success { background: linear-gradient(90deg, #22c55e, #16a34a); }
        .bar.redirect { background: linear-gradient(90deg, #f59e0b, #d97706); }
        .bar.client-error { background: linear-gradient(90deg, #ef4444, #dc2626); }
        .bar.server-error { background: linear-gradient(90deg, #dc2626, #b91c1c); }
        .bar.unknown { background: linear-gradient(90deg, #6b7280, #4b5563); }
        .bar.error { box-shadow: 0 0 8px rgba(239, 68, 68, 0.6); }

        .main-request .bar {
            opacity: 0.3;
        }

        .events-list {
            margin-top: 2rem;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9rem;
        }

        th, td {
            padding: 0.8rem;
            text-align: left;
            border-bottom: 1px solid rgba(255,255,255,0.1);
        }

        th {
            color: #94a3b8;
            font-weight: 500;
        }

        tr:hover {
            background: rgba(255,255,255,0.05);
        }

        footer {
            margin-top: 3rem;
            text-align: center;
            color: #64748b;
            font-size: 0.85rem;
        }
    '''


def _get_js() -> str:
    """Get embedded JavaScript."""
    return '''
        // Interactive features can be added here
        document.querySelectorAll('.bar').forEach(bar => {
            bar.addEventListener('click', () => {
                // Could show detailed popup
            });
        });
    '''
